"""Browser lifecycle contracts and backend implementations."""

from lex_browser_runtime.browser.backends import (
    BrowserBackend,
    ExistingCdpBackend,
    LexmountBackend,
)
from lex_browser_runtime.browser.actions import (
    BrowserActionResult,
    BrowserActionTarget,
    ClickRequest,
    EvalRequest,
    OpenUrlRequest,
    ScreenshotRequest,
    SnapshotRequest,
    TypeRequest,
    WaitSelectorRequest,
    execute_browser_action_on_page,
    resolve_browser_action_connect_url,
    run_browser_action,
)
from lex_browser_runtime.browser.cases import (
    CaseRunSummary,
    CaseStepRunResult,
    CaseTargetResolution,
    CaseValidationResult,
    load_case_file,
    run_case_file,
    run_case_step,
    validate_case_file,
    validate_case_spec,
)
from lex_browser_runtime.browser.lexmount import (
    ContextListResult,
    LexmountBrowserAdmin,
    LexmountContextRecord,
    LexmountErrorInfo,
    LexmountPaginationInfo,
    LexmountSessionRecord,
    SessionCreateResult,
    SessionListResult,
    build_direct_connect_url,
    normalize_lexmount_sdk_error,
)
from lex_browser_runtime.browser.models import (
    BrowserAuthError,
    BrowserConfigError,
    BrowserParallelLimitError,
    BrowserRuntimeError,
    BrowserSessionInfo,
    CreateBrowserRequest,
)

__all__ = [
    "BrowserAuthError",
    "BrowserBackend",
    "BrowserConfigError",
    "BrowserActionResult",
    "BrowserActionTarget",
    "BrowserParallelLimitError",
    "BrowserRuntimeError",
    "BrowserSessionInfo",
    "CaseRunSummary",
    "CaseStepRunResult",
    "CaseTargetResolution",
    "CaseValidationResult",
    "ClickRequest",
    "ContextListResult",
    "CreateBrowserRequest",
    "EvalRequest",
    "ExistingCdpBackend",
    "LexmountBrowserAdmin",
    "LexmountBackend",
    "LexmountContextRecord",
    "LexmountErrorInfo",
    "LexmountPaginationInfo",
    "LexmountSessionRecord",
    "OpenUrlRequest",
    "ScreenshotRequest",
    "SessionCreateResult",
    "SessionListResult",
    "SnapshotRequest",
    "TypeRequest",
    "WaitSelectorRequest",
    "build_direct_connect_url",
    "execute_browser_action_on_page",
    "load_case_file",
    "normalize_lexmount_sdk_error",
    "resolve_browser_action_connect_url",
    "run_case_file",
    "run_case_step",
    "run_browser_action",
    "validate_case_file",
    "validate_case_spec",
]
